In [1]:
from chatbot import ask
import pandas as pd
import random
queries = pd.read_csv(filepath_or_buffer = "Data/source/vnuis.csv",usecols =["Question 1"])
queries.dropna(inplace=True)
queries.drop_duplicates(inplace=True)
queries = queries["Question 1"].to_list()

queries = random.sample(queries, 50)
list_result = []

/home/admin-hieunn/important/VNUIS-Chatbot/.venv/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange
2025-01-17 11:51:50,825 - INFO - Load pretrained SentenceTransformer: BAAI/bge-m3


Using cuda
Loading models... 


2025-01-17 11:51:54,917 - INFO - Done TTS
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.23it/s]


Models Loaded!


In [2]:
for query in queries:
    a = ask(query)
    list_result.append(a)
array_2d = list(zip(queries, list_result))

df_result = pd.DataFrame(data = array_2d, columns=["Question", "Answer"])
df_result.to_csv(path_or_buf = "Data/Evaluation/evaluation.csv")

Batches: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]

tensor([0.7461, 0.7422, 0.7422, 0.7383, 0.6719, 0.6602, 0.6602, 0.6562, 0.6523,
        0.6484, 0.6484, 0.6445, 0.6445, 0.6406, 0.6367, 0.6328, 0.6289, 0.6289,
        0.6250, 0.6250], device='cuda:0', dtype=torch.bfloat16)



The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Starting from v4.46, the `logits` model output will have the same type as the model (except at train time, where it will always be FP32)
Batches: 100%|██████████| 1/1 [00:00<00:00, 144.21it/s]


tensor([0.8750, 0.8516, 0.8359, 0.8164, 0.7969, 0.7773, 0.7656, 0.7656, 0.7500,
        0.7344, 0.7344, 0.7188, 0.7070, 0.6992, 0.6953, 0.6914, 0.6914, 0.6875,
        0.6875, 0.6836], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 178.97it/s]


tensor([0.7500, 0.7266, 0.7227, 0.7188, 0.7109, 0.6523, 0.6328, 0.6289, 0.6289,
        0.6250, 0.6211, 0.6211, 0.6211, 0.6172, 0.6133, 0.6133, 0.6133, 0.6133,
        0.6094, 0.6094], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 228.32it/s]


tensor([0.7383, 0.7344, 0.7188, 0.7148, 0.6445, 0.6328, 0.6172, 0.6094, 0.6094,
        0.6094, 0.6055, 0.6016, 0.6016, 0.6016, 0.5977, 0.5938, 0.5898, 0.5898,
        0.5898, 0.5859], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 224.20it/s]


tensor([0.7891, 0.7500, 0.7109, 0.7031, 0.6953, 0.6875, 0.6797, 0.6758, 0.6758,
        0.6602, 0.6602, 0.6484, 0.6406, 0.6328, 0.6289, 0.6289, 0.6250, 0.6211,
        0.6211, 0.6211], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 88.67it/s]


tensor([0.7578, 0.7500, 0.7422, 0.7383, 0.7266, 0.7266, 0.7266, 0.7266, 0.7188,
        0.7188, 0.7188, 0.7148, 0.7148, 0.7148, 0.7148, 0.7109, 0.7109, 0.7109,
        0.7109, 0.7109], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 238.07it/s]


tensor([0.7539, 0.7227, 0.7070, 0.7070, 0.7031, 0.6992, 0.6992, 0.6953, 0.6914,
        0.5469, 0.5469, 0.5469, 0.5430, 0.5430, 0.5391, 0.5391, 0.5391, 0.5391,
        0.5391, 0.5391], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 224.35it/s]


tensor([0.7539, 0.7539, 0.7461, 0.7422, 0.7422, 0.7422, 0.7383, 0.7305, 0.7305,
        0.6875, 0.5625, 0.5586, 0.5547, 0.5547, 0.5547, 0.5547, 0.5508, 0.5430,
        0.5352, 0.5156], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 224.02it/s]


tensor([0.6680, 0.6367, 0.6250, 0.6133, 0.6094, 0.6055, 0.6016, 0.6016, 0.6016,
        0.5977, 0.5977, 0.5938, 0.5859, 0.5820, 0.5820, 0.5820, 0.5820, 0.5820,
        0.5742, 0.5742], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 224.40it/s]


tensor([0.6523, 0.6523, 0.6484, 0.6289, 0.6211, 0.6172, 0.6172, 0.6133, 0.6133,
        0.6094, 0.6055, 0.6016, 0.5977, 0.5898, 0.5898, 0.5859, 0.5859, 0.5859,
        0.5859, 0.5859], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 231.44it/s]


tensor([0.7852, 0.7773, 0.7656, 0.7539, 0.7383, 0.7305, 0.7266, 0.7266, 0.7188,
        0.7070, 0.7070, 0.7031, 0.7031, 0.6992, 0.6914, 0.6914, 0.6914, 0.6875,
        0.6875, 0.6836], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 229.13it/s]


tensor([0.7305, 0.7148, 0.7148, 0.7070, 0.6758, 0.6758, 0.6680, 0.6641, 0.6641,
        0.6484, 0.6445, 0.6328, 0.6328, 0.6211, 0.6133, 0.6133, 0.6094, 0.6094,
        0.6055, 0.6055], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 227.19it/s]


tensor([0.7930, 0.7773, 0.7383, 0.7031, 0.6914, 0.6758, 0.6719, 0.6680, 0.6680,
        0.6641, 0.6602, 0.6562, 0.6484, 0.6484, 0.6445, 0.6406, 0.6367, 0.6367,
        0.6367, 0.6367], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 237.77it/s]


tensor([0.7305, 0.7266, 0.7227, 0.7227, 0.7227, 0.7188, 0.7109, 0.6992, 0.6992,
        0.6914, 0.6914, 0.6250, 0.5664, 0.5586, 0.5586, 0.5586, 0.5547, 0.5508,
        0.5508, 0.5508], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 219.80it/s]


tensor([0.7109, 0.6992, 0.6992, 0.6953, 0.6953, 0.6914, 0.6914, 0.6836, 0.6836,
        0.6836, 0.6797, 0.6758, 0.6641, 0.6641, 0.6602, 0.6562, 0.6562, 0.6445,
        0.6445, 0.6367], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 185.31it/s]


tensor([0.8320, 0.8242, 0.7969, 0.7969, 0.7930, 0.7891, 0.7148, 0.7031, 0.7031,
        0.6992, 0.6914, 0.6914, 0.6836, 0.6758, 0.6602, 0.6562, 0.6523, 0.6445,
        0.6445, 0.6406], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 220.46it/s]


tensor([0.7227, 0.6484, 0.6445, 0.6094, 0.6094, 0.5273, 0.5234, 0.5117, 0.4980,
        0.4961, 0.4941, 0.4922, 0.4902, 0.4902, 0.4863, 0.4863, 0.4863, 0.4863,
        0.4844, 0.4824], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 224.19it/s]


tensor([0.7383, 0.7305, 0.7266, 0.7070, 0.6836, 0.6836, 0.6758, 0.6719, 0.6719,
        0.6641, 0.6641, 0.6562, 0.6484, 0.6484, 0.6445, 0.6406, 0.6289, 0.6289,
        0.6250, 0.6211], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 238.76it/s]


tensor([0.7656, 0.7617, 0.7500, 0.7422, 0.7148, 0.7070, 0.7031, 0.6992, 0.6953,
        0.6836, 0.6758, 0.6758, 0.6758, 0.6719, 0.6719, 0.6719, 0.6211, 0.6172,
        0.6172, 0.6133], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 217.37it/s]


tensor([0.8242, 0.7617, 0.7578, 0.7539, 0.7500, 0.7461, 0.7461, 0.7422, 0.7422,
        0.7383, 0.7383, 0.7305, 0.7305, 0.7305, 0.7305, 0.7305, 0.7266, 0.7227,
        0.7227, 0.7227], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 219.47it/s]


tensor([0.7500, 0.7031, 0.6992, 0.6797, 0.6758, 0.6680, 0.6641, 0.6641, 0.6641,
        0.6602, 0.6562, 0.6523, 0.6484, 0.6445, 0.6445, 0.6445, 0.6406, 0.6328,
        0.6328, 0.6250], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 208.86it/s]


tensor([0.7812, 0.7266, 0.7031, 0.6797, 0.6758, 0.6680, 0.6641, 0.6445, 0.6406,
        0.6094, 0.6055, 0.6055, 0.5977, 0.5977, 0.5977, 0.5898, 0.5898, 0.5859,
        0.5820, 0.5781], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 219.09it/s]


tensor([0.8281, 0.7695, 0.7695, 0.7500, 0.7344, 0.7227, 0.7227, 0.7227, 0.7188,
        0.7109, 0.7070, 0.7070, 0.7070, 0.7070, 0.7031, 0.7031, 0.7031, 0.6953,
        0.6836, 0.6836], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 224.84it/s]


tensor([0.8359, 0.8281, 0.8242, 0.8047, 0.7539, 0.7539, 0.7461, 0.7344, 0.7344,
        0.7188, 0.7109, 0.7109, 0.7031, 0.6680, 0.6523, 0.6484, 0.6445, 0.6367,
        0.6133, 0.6055], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 189.14it/s]


tensor([0.7109, 0.7109, 0.7031, 0.6953, 0.6523, 0.6445, 0.6445, 0.6367, 0.6250,
        0.6211, 0.6133, 0.6133, 0.6094, 0.6094, 0.6094, 0.6094, 0.6055, 0.6016,
        0.5898, 0.5898], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 236.93it/s]


tensor([0.7383, 0.7305, 0.7305, 0.7266, 0.6758, 0.6758, 0.6680, 0.6602, 0.5898,
        0.5898, 0.5859, 0.5781, 0.5781, 0.5781, 0.5742, 0.5742, 0.5742, 0.5742,
        0.5742, 0.5703], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 229.16it/s]


tensor([0.7812, 0.7734, 0.7695, 0.7656, 0.7617, 0.7578, 0.7539, 0.7422, 0.7344,
        0.7305, 0.7305, 0.7266, 0.7227, 0.7148, 0.7148, 0.7148, 0.5391, 0.5195,
        0.5117, 0.5117], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 218.15it/s]


tensor([0.5781, 0.5703, 0.5273, 0.5273, 0.5273, 0.5000, 0.4902, 0.4883, 0.4883,
        0.4824, 0.4824, 0.4824, 0.4805, 0.4805, 0.4805, 0.4805, 0.4785, 0.4785,
        0.4766, 0.4746], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 207.21it/s]


tensor([0.7656, 0.7617, 0.7539, 0.7500, 0.7461, 0.7383, 0.7383, 0.7305, 0.7266,
        0.7227, 0.7227, 0.7227, 0.7188, 0.7188, 0.7188, 0.7148, 0.7148, 0.7109,
        0.7109, 0.7109], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 221.32it/s]


tensor([0.8398, 0.8359, 0.8359, 0.8242, 0.8242, 0.8242, 0.8125, 0.8086, 0.8086,
        0.8008, 0.8008, 0.8008, 0.7969, 0.7969, 0.7930, 0.7930, 0.7930, 0.7812,
        0.7773, 0.7734], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 228.26it/s]


tensor([0.8047, 0.7578, 0.7539, 0.7500, 0.7383, 0.7344, 0.7344, 0.7305, 0.7227,
        0.7188, 0.7148, 0.7109, 0.6953, 0.6914, 0.6875, 0.6875, 0.6875, 0.6797,
        0.6797, 0.6758], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 234.42it/s]


tensor([0.7617, 0.7305, 0.6562, 0.6484, 0.6445, 0.6250, 0.6250, 0.6250, 0.6211,
        0.6211, 0.6172, 0.6094, 0.6094, 0.6016, 0.5977, 0.5977, 0.5938, 0.5781,
        0.5781, 0.5742], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 213.05it/s]


tensor([0.8398, 0.7852, 0.7734, 0.7539, 0.7539, 0.7539, 0.7422, 0.7188, 0.6992,
        0.6953, 0.6758, 0.6719, 0.6680, 0.6641, 0.6602, 0.6602, 0.6562, 0.6562,
        0.6562, 0.6523], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 226.43it/s]


tensor([0.8086, 0.7578, 0.7578, 0.7539, 0.7422, 0.7383, 0.7344, 0.7344, 0.7344,
        0.7305, 0.7266, 0.7227, 0.7188, 0.7148, 0.7148, 0.7109, 0.7109, 0.7109,
        0.7070, 0.7070], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 201.27it/s]


tensor([0.8086, 0.7969, 0.7930, 0.7422, 0.7344, 0.7344, 0.7344, 0.7344, 0.7305,
        0.6953, 0.6953, 0.6914, 0.6367, 0.6328, 0.6289, 0.6289, 0.6250, 0.6211,
        0.6211, 0.6172], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 219.39it/s]


tensor([0.7109, 0.7109, 0.7070, 0.6758, 0.6719, 0.6719, 0.6680, 0.6680, 0.6602,
        0.6562, 0.6523, 0.6484, 0.6250, 0.6211, 0.6211, 0.6172, 0.6172, 0.6172,
        0.6172, 0.6133], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 184.87it/s]


tensor([0.7734, 0.6875, 0.6406, 0.6367, 0.6367, 0.6328, 0.6211, 0.6172, 0.6133,
        0.6094, 0.6055, 0.6055, 0.6055, 0.6055, 0.6055, 0.6055, 0.6055, 0.5977,
        0.5977, 0.5977], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 236.13it/s]


tensor([0.7773, 0.7422, 0.7383, 0.7344, 0.7305, 0.7109, 0.7070, 0.7070, 0.6992,
        0.6953, 0.6914, 0.6875, 0.6797, 0.6797, 0.6758, 0.6758, 0.6758, 0.6641,
        0.6641, 0.6641], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 227.24it/s]


tensor([0.8398, 0.7969, 0.7930, 0.7930, 0.7930, 0.7891, 0.7852, 0.7812, 0.7812,
        0.6328, 0.6250, 0.6133, 0.6094, 0.6055, 0.6016, 0.5938, 0.5938, 0.5898,
        0.5898, 0.5859], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 220.92it/s]


tensor([0.7578, 0.7188, 0.6992, 0.6953, 0.6914, 0.6914, 0.6875, 0.6875, 0.6797,
        0.6797, 0.6797, 0.6758, 0.6758, 0.6758, 0.6719, 0.6719, 0.6719, 0.6719,
        0.6680, 0.6641], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 225.22it/s]


tensor([0.7344, 0.7266, 0.7227, 0.7109, 0.6289, 0.6250, 0.6133, 0.6055, 0.6055,
        0.6055, 0.6016, 0.5977, 0.5977, 0.5977, 0.5938, 0.5898, 0.5898, 0.5898,
        0.5859, 0.5820], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 209.28it/s]


tensor([0.8242, 0.6914, 0.6445, 0.6406, 0.6289, 0.6250, 0.6250, 0.6211, 0.6211,
        0.6094, 0.6094, 0.6094, 0.6055, 0.6016, 0.5859, 0.5820, 0.5820, 0.5742,
        0.5703, 0.5664], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 217.78it/s]


tensor([0.8047, 0.7656, 0.7578, 0.7500, 0.7461, 0.7383, 0.6758, 0.6719, 0.6484,
        0.6445, 0.6445, 0.6406, 0.6367, 0.6367, 0.6328, 0.6328, 0.6328, 0.6328,
        0.6289, 0.6250], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 233.30it/s]


tensor([0.7305, 0.6719, 0.6406, 0.6406, 0.6289, 0.6289, 0.6250, 0.6211, 0.6172,
        0.6172, 0.6172, 0.6172, 0.6133, 0.6094, 0.6094, 0.6055, 0.5977, 0.5977,
        0.5977, 0.5977], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 218.33it/s]


tensor([0.8125, 0.8047, 0.8047, 0.8047, 0.8008, 0.8008, 0.7969, 0.7891, 0.7852,
        0.7695, 0.7461, 0.6836, 0.6797, 0.6758, 0.6719, 0.6680, 0.6680, 0.6680,
        0.6680, 0.6641], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 236.65it/s]


tensor([0.7188, 0.7070, 0.7031, 0.6914, 0.6758, 0.6602, 0.6602, 0.6602, 0.6562,
        0.6562, 0.6523, 0.6484, 0.6445, 0.6445, 0.6367, 0.6328, 0.6289, 0.6250,
        0.6211, 0.6172], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 223.51it/s]


tensor([0.7695, 0.7539, 0.7148, 0.6953, 0.6875, 0.6875, 0.6797, 0.6680, 0.6680,
        0.6641, 0.6641, 0.6562, 0.6562, 0.6562, 0.6562, 0.6523, 0.6523, 0.6484,
        0.6484, 0.6484], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 221.77it/s]


tensor([0.8125, 0.7969, 0.7969, 0.7852, 0.7773, 0.7773, 0.7539, 0.7539, 0.7422,
        0.7422, 0.7422, 0.7344, 0.7344, 0.7266, 0.7227, 0.7227, 0.7227, 0.7188,
        0.7188, 0.6953], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 187.03it/s]


tensor([0.8008, 0.7305, 0.7227, 0.6680, 0.6484, 0.6367, 0.6289, 0.6172, 0.6055,
        0.5781, 0.5664, 0.5664, 0.5625, 0.5586, 0.5586, 0.5586, 0.5586, 0.5586,
        0.5547, 0.5547], device='cuda:0', dtype=torch.bfloat16)


Batches: 100%|██████████| 1/1 [00:00<00:00, 226.82it/s]


tensor([0.7695, 0.7305, 0.6797, 0.6758, 0.6758, 0.6719, 0.6641, 0.6641, 0.6562,
        0.6562, 0.6523, 0.6523, 0.6445, 0.6367, 0.6289, 0.6250, 0.6211, 0.6133,
        0.6133, 0.6133], device='cuda:0', dtype=torch.bfloat16)
